# Generated by Django 4.1 on 2022-08-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_subscriber_unique email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriber',
            name='Unique email',
        ),
    ]
