# Generated by Django 4.1 on 2022-08-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_subscriber_unique email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='unsubscribe_code',
            new_name='unsub_code',
        ),
    ]
